### ISSUE TITLE
Webserial API two way communication via serial port

### ISSUE THREAD

**Issue by rennemannd** [STEM-C/CaSMM#122]
Story
As a workspace user I should be able to receive feedback from the interface in some way based on pre-determined events occurring with the hardware.

Implementation
Currently we have no way to communicate back from webserial API using the avrgirl library. There are currently no viable alternatives so the easiest solution is believed to include re-writing significant parts of the avrgirl library to more fully integrate with webserial-api and provide the additional functionality we require (this is unsurprising as avrgirl was originally intended for node.js and jury-rigged to work in browser). 

A working alternative to avrgirl needs to be created that has the same basic functionality we currently use:
- [x] Library can flash arduino uno board with block code
- [x] Library can flash similar arduino boards using different protocols

Once these requirements are met the library then needs to be expanded to be able to:
- [x] Establish a serial port connection for an extended duration through the browser
- [ ] Receive feedback from hardware based on external stimulus, this can be a basic popup for now
 

client - On undo, pop from the local storage stack and set the canvas to that

**Comment by rennemannd** [comment]
I have written a basic version of the library confirming the above is possible, the next step is moving it over to an organization repository for further development. There is a lot of refactoring that needs to be done to get things working cleanly so I have made it into a new issue to be checked off as the mini milestones are reached using the main CaSMM repo with the library.

**Comment by syuChen1** [comment]
Serial API implement without the need to re-write the avrgirl library
