### ISSUE TITLE
Content Creator View

### ISSUE THREAD

**Issue by rennemannd** [STEM-C/CaSMM#124]
Currently the content creator view is undecided and there are no mock-ups. Before moving forward a basic layout and understanding of their tasks should be completed. The following should later be broken down into separate cards once this layout is more formalized: 

The Content creator should be able to do the following: 
 - Choose blocks from menu
 - Choose block canvas shown
 - Save everything as one activity
 - Upload content to menu for teachers to see
 - Edit lessons that already exist
 - Student view for lessons 
 - Perform some type of animation mapping based on arduino output 

The Content creator would like to do the following: 
 - Copy something from another lesson
 - Copy XML as an option
 - Duplicate a lesson

Discussion:
 - Can content creator see student submissions?
 - Who gets content-creator content? Do all teachers see all content or does the CC assign the content?
 - Teachers/Mentors can't make changes to lessons for now. Need to request help from CC, should this change? 
 - If a fix is pushed, do they refresh to see this? Does their (student) project get wiped?

**Comment by gussegovia98** [comment]
Addressed in #134
