### ISSUE TITLE
Reading in analog sensor values from Arduino and Displaying value for students

### ISSUE THREAD

**Issue by cgardnermccune** [STEM-C/CaSMM#132]
As we prepare for a Spring 2020 software roll-out we need to build functionality that allows our web application to read in values from the arduino and display it real-time maybe in a pop-up message. Test cases reading from a humidity sensor.

This issue has back-end and front-end functionality.

Sample read:
https://www.arduino.cc/reference/en/language/functions/communication/serial/read/

**Comment by syuChen1** [comment]
Controller: 
- [x] Read and print serial output to console.
- [ ] Create event listener for device disconnection.

View: 
- [ ] Create console view to display output.
- [ ] Create a baud rate option to connect to a specific baud rate.

Optional: 
- [ ] Create input section to send input to Arduino board.
