### ISSUE TITLE
Research for updating data models in production

### ISSUE THREAD

**Issue by MeghaNagarmunoli** [STEM-C/CaSMM#158]
**Story:**
Right now the Data Model must be manually updated in Staging and Production.
We need this to be automated with every each release.

**Implementation**
- [x] Read Strapi documentation for a solution.
- [ ] Document the possible ways it can be achieved.

**Comment by syuChen1** [comment]
https://portal.productboard.com/strapi/1-roadmap/c/12-data-migration-across-environments?utm_medium=social&utm_source=portal_share
Strapi has planned features for data migration across environments in the future. But right now the best way is to update the database model manually.
