### ISSUE TITLE
Student Role UI changes 01

### ISSUE THREAD

**Issue by jimenyer** [STEM-C/CaSMM#173]
**Describe the bug**

- [x] Font and color for "select your day" label needs to be change 
- [x] Lessons are not in order
- [x] Lessons are  duplicated 

**To Reproduce**
1. Login as a student 
2. Select a name and animal 
3. Click on 'Enter'

**Expected behavior**

- [x] Chance the color of “Select your day” to white 
- [x] Decreases the font size of “Select your day”  
- [x] Lessons must be in order
- [x] Lessons must not be duplicated 

**Screenshots**

<img width="623" alt="Screen Shot 2021-03-24 at 12 11 34 PM" src="https://user-images.githubusercontent.com/30293586/112347072-f2ba1400-8c9c-11eb-894f-7246db20feea.png">

**Comment by chensation** [comment]
unable to replicate the duplicate lesson issue. Likely a backend data problem.
