### ISSUE TITLE
Content Creator UI Updates/Interactions

### ISSUE THREAD

**Issue by le-anna** [STEM-C/CaSMM#218]
**Content Creator**
- [x] Update subheading/buttons to match new style guide
![image](https://user-images.githubusercontent.com/70594602/123675270-85280180-d810-11eb-94ea-d2eb243664cb.png)
- [x] Switch order of unit and learning standard display in table
- [x] Quick look window (delete "Add" and "Number)
- [x] Change module labels 
- [x] Create new module called "Add Selected Day Lesson Details" 
![image](https://user-images.githubusercontent.com/70594602/123674748-f31ff900-d80f-11eb-84f9-6ce6d7a009f0.png)
- [x] Update and connect new interactions between the different modules (Add Learning Standard and Quick Look views)
![image](https://user-images.githubusercontent.com/70594602/123675063-4eea8200-d810-11eb-8480-31ac3c94dbd5.png)
![image](https://user-images.githubusercontent.com/70594602/123675137-632e7f00-d810-11eb-8451-a997ec03981f.png)

**Comment by syuChen1** [comment]
@syuChen1  
- [ ] create day information backend

**Comment by syuChen1** [comment]
Update day lesson detail API created #287

**Comment by syuChen1** [comment]
## content creator
- [ ] Display learning components in day detail
- [ ] Editing learning components as tags in the frontend
- [ ] learning components backend

## Mentor
- [ ] Display learning components

@le-anna: 
- [ ] UI changes to display day info
- [ ] Response design for phones and tablets
