### ISSUE TITLE
Staging and production monitoring

### ISSUE THREAD

**Issue by nionata** [STEM-C/CaSMM#22]
- [x] Create a heroku slack channel
- [ ] Create a slack app w/ incoming web hooks
- [ ] Setup web hooks on heorku
- [ ] Create CMS endpoint to handle data transformation

**Comment by nionata** [comment]
I started working on this. Created a slack app and enabled incoming webhooks. The expected payload needs to be formatted from the raw payload sent from heroku. We will probably want to expose an endpoint on cms to handle this. For now, it can be delayed.

**Comment by syuChen1** [comment]
Created slack channel and Added Sentry #43
