### ISSUE TITLE
User Logging

### ISSUE THREAD

**Issue by cgardnermccune** [STEM-C/CaSMM#36]
We need a way to track student progress on activities. Block picked up, deleted, state of blocks when he/she runs the code, modifications etc. 

These logs will be used to analyze student usage of the tool from a learning an a usability perspective.

**Comment by nionata** [comment]
@cgardnermccune If this is anonymized usage data then we can use google analytics and custom events. If we want to track usage by a specific classroom/student, we are going to have to roll our own solution using something like elastic search. The later approach might also come into issues with COPPA.

**Comment by nionata** [comment]
Related #32
