### ISSUE TITLE
System Logging - Readable Issues for Production Support

### ISSUE THREAD

**Issue by cgardnermccune** [STEM-C/CaSMM#43]
We need to think of the ways that the application might fail and create readable issues that allow us to quickly identify issues and fixes to reduce downtime or system failure while in production.

- [ ] common ways users can crash the system
- [ ] bugs that are likely to cause system crash
- [ ] create reable issues to slackbot can report so that we can quickly address them

**Comment by nionata** [comment]
Convo w/ an engineer at my previous work about using [Sentry](https://sentry.io/welcome/) for error monitoring:

![Screen Shot 2020-06-03 at 12 58 22 PM](https://user-images.githubusercontent.com/9022220/83666402-e6908900-a59a-11ea-93b1-b68e1b28e6bd.png)

A solution like this would give us robust full-stack error monitoring with little implementation on our end.

**Comment by syuChen1** [comment]
Connected Sentry to the project
