### ISSUE TITLE
Capture Student Submissions

### ISSUE THREAD

**Issue by nionata** [STEM-C/CaSMM#6]
- [x] Update documentation

**Server**
- [x] Create submission content type
- [x] Add REDIS docker service
- [x] connect to queue on start
- [x] Override the create controller to add to queue
- [x] Create sandbox endpoints

**Compile**
- [x] rewrite compile to pull from queue

**Automation**
- [x] add redis addon to review app create
- [x] build and use compile image

**Client**
- [x] On upload code
  - [x] create a save
  - [x] `POST /submissions` with the `{ day: dayId, workspace: "block code", board: "arduino:avr:uno", sketch: "arduino code" }`
- [x] After submitting make sequential `GET /submissions/:submission-id` till `status` is `COMPLETED` (hex will be in the final request response)

**Comment by nionata** [comment]
![leet](https://user-images.githubusercontent.com/9022220/83977655-2e334f80-a8d0-11ea-9d49-262435721071.PNG)

Leetcode, a cloud based competitive coding site w/ a multiple language cloud compiler, uses a queuing/worker architecture for compiling and verifying code. From the above screenshot, you can see the the initial submission is a post request and a submission id is returned. From there, /check requests are made to check the status of the submission until it is finally returned. This is the exact method that I am proposing we make our compiler.

Benefits:
- Compile has no database module - we would have to write dataaccess code that already exists in cms to add metrics and save compiles
- Compile has no way of checking if someone has submitted recently - if we had it connected to a db like in cms, it would be trivial 
- The compiler has no authentication and can be accessed via HTTP by anyone - cms has all of that build out

By routing all of the submissions through cms, we will be able to easily implement a lot of great features (submission tracking, submission limiting, authentication, etc). The compiler will be inaccessible via http, shrinking our attack surface. Additionally, it will be more scalable to run the compiler as a worker feeding from a shared in-memory queue. To make it even more fault tolerant, we can add a dead-letter queue for jobs that won't compile and we want to revisit later.

I have added this to v1.0 because we will be implementing our authentication in v0.3. By doing this after auth, we can ensure we take advantage of all the benefits of this conversion.

**Comment by nionata** [comment]
<img width="529" alt="stem-c-sessions-relationship" src="https://user-images.githubusercontent.com/9022220/90296188-d2012480-de58-11ea-96bd-3ecd288f6535.PNG">
This original schema is not going to work because we don't need the same redundancy with submissions as we do saves. This will be refactored to connect submission with session and activity (day)

**Comment by tamargoadam** [comment]
The new schema for submissions, referenced by Nick, is as follows:
![image](https://user-images.githubusercontent.com/26982897/90405390-ac029c80-e071-11ea-8d37-c499e40da21b.png)

**Comment by nionata** [comment]
The [bull](https://www.npmjs.com/package/bull) queue has a progress value (0-100) that we can update and listen to. The server will be listening to global changes to progress and update the submission entry status in the db. 
``` 
0: CREATED
50: COMPILING
100: COMPLETED
```

**Comment by nionata** [comment]
![Screen Shot 2020-08-18 at 2 47 06 PM](https://user-images.githubusercontent.com/9022220/90558549-3fb79400-e16a-11ea-9741-da8c40537eaa.png)

Rough flow for submissions
