### ISSUE TITLE
Admin Roles & Permissions

### ISSUE THREAD

**Issue by nionata** [STEM-C/CaSMM#91]
Strapi just [released](https://strapi.io/blog/announcing-3.1-role-based-access-control?utm_campaign=Strapi%20Weekly&utm_medium=email&_hsmi=91908704&_hsenc=p2ANqtz-_xQT7SRCBHUYUPD8uVsC0UevgBKdqcl-_v9WT4yO1oZJx711cGG8ab7UfjxOAL9QZcwEBNF2WmEewwL2zxW3zn0O36kg&utm_content=91908704&utm_source=hs_email) Administrator Roles & Permission. We can
- [x] Update to strapi 3.1
- [ ] Setup content creator accs

**Comment by syuChen1** [comment]
Strapi update complete. We implemented our own content creator page. But it's nice to take a closer look and see what  Administrator Roles & Permission can bring us.
